default_platform(:android)

APP_ID = "1:509695284070:android:163e43b4c5c6ad7bc52ea7"
FIREBASE_TOKEN = "1//0hvh_Z6GV0INJCgYIARAAGBESNwF-L9Ir1WDKKn4wj_Vp1UNCCTIRZ-tLH04GFWJmvAbr2l2fsjCNvSqCdS29FCJhr5ojix3FiFw"
BUILD_NUMBER = "1"

platform :android do
  desc "Deploy a new beta"
      gradle(
          task: 'assemble',
          build_type: 'Release'
      )
  lane :distribute_beta do
      firebase_app_distribution(
          app: APP_ID,
          testers: "ri.da.igle.es@gmail.com",
          release_notes: BUILD_NUMBER,
          firebase_cli_path: "/usr/local/bin/firebase",
          firebase_cli_token: FIREBASE_TOKEN,
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
end