// Generated by https://quicktype.io

class Team {
  int id;
  String name;
  int teamSize;
  int hoursPlayed;
  int levelAverage;

  Team({
    required this.id,
    required this.name,
    required this.teamSize,
    required this.hoursPlayed,
    required this.levelAverage,
  });
  // Parsing data from json for networking
  factory Team.fromJson(Map<String, dynamic> map) {
    return Team(
        id: map['id'],
        name: map['name'],
        teamSize: map['teamSize'],
        hoursPlayed: map['hoursPlayed'],
        levelAverage: map['levelAverage']);
  }

  // Serializing to map for local persistence
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'teamSize': teamSize,
      'hoursPlayed': hoursPlayed,
      'levelAverage': levelAverage
    };
  }

  // Parsing data from map for local persistence
  factory Team.fromMap(Map<String, dynamic> map) {
    return Team(
      id: map['id'],
      name: map['name'],
      teamSize: map['overview'],
      hoursPlayed: map['path'],
      levelAverage: map['levelAverage'],
    );
  }
}
