// Generated by https://quicktype.io

class Team {
  int id;
  String name;
  int teamSize;
  int hoursPlayed;
  int levelAverage;

  Team({
    this.id,
    this.name,
    this.teamSize,
    this.hoursPlayed,
    this.levelAverage,
  });

  Team.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    teamSize = json['teamSize'];
    hoursPlayed = json['hoursPlayed'];
    levelAverage = json['levelAverage'];
  }

  // Parsing data from json for networking
  factory Team.fromJson(Map<String, dynamic> map) {
    return Team(
        id: map['id'],
        name: map['name'],
        teamSize: map['teamSize'],
        hoursPlayed: map['hoursPlayed'],
        levelAverage: map['levelAverage']);
  }

  // Serializing to map for local persistence
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'teamSize': teamSize,
      'hoursPlayed': hoursPlayed,
      'levelAverage': levelAverage
    };
  }

  // Parsing data from map for local persistence
  factory Team.fromMap(Map<String, dynamic> map) {
    return Team(
      id: map['id'],
      name: map['name'],
      teamSize: map['overview'],
      hoursPlayed: map['path'],
      levelAverage: map['levelAverage'],
    );
  }
}
